apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-namespace-backup
roleRef:
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: cron-namespace-backup-sa
  namespace: "cluster-operations"

