kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-claim
  namespace: cluster-operations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
