apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-prune-runner
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cron-prune-runner-sa
  namespace: "cluster-operations"

