apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prune-images
  namespace: cluster-operations
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
          containers:
          - name: prune-images
            image: registry.redhat.io/openshift4/ose-cli:v4.7
            command:
            - /bin/bash
            - -c
            - |
              #/bin/bash
              oc adm prune images --keep-tag-revisions=3 --keep-younger-than=60m --force-insecure --confirm
              oc adm prune images --prune-over-size-limit --force-insecure --confirm
            imagePullPolicy: Always
            env:
            - name: HOME
              value: "/tmp"
          restartPolicy: OnFailure
          serviceAccountName: cron-prune-runner-sa
          imagePullSecrets:
          - name: xyz-user-pull-secret
